<?php
/* TimeWalk Japan module: Meetup events and English site presentation */
if (!defined('ABSPATH')) exit;
final class TWJ_Meetup_Module {
 const CSV='https://docs.google.com/spreadsheets/d/e/2PACX-1vRRCxTcvP_OdDabsRBhNEFzXKJlKN_6Z-5Zd6E4tG9UxMgZPUkL_6-hGxG4RDvoWUd0_lrVUF049S03/pub?gid=1954885293&single=true&output=csv';
 function __construct(){add_shortcode('timewalk_meetup_events',array($this,'shortcode'));add_action('wp_enqueue_scripts',array($this,'assets'));}
 private function urls(){ $r=wp_remote_get(self::CSV,array('timeout'=>15)); if(is_wp_error($r))return array(); $out=array(); foreach(preg_split('/\r\n|\r|\n/',trim((string)wp_remote_retrieve_body($r))) as $row){$cols=str_getcsv($row);$u=isset($cols[0])?trim((string)$cols[0]):'';if(strpos($u,'https://www.meetup.com/yuru-rekishi/events/')===0)$out[]=$u;} return array_unique($out); }
 private function card($url){ $r=wp_remote_get($url,array('timeout'=>20,'headers'=>array('User-Agent'=>'Mozilla/5.0'))); if(is_wp_error($r))return'';$h=(string)wp_remote_retrieve_body($r);preg_match('/<meta[^>]+property=["\']og:title["\'][^>]+content=["\']([^"\']+)/i',$h,$t);preg_match('/<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']+)/i',$h,$i);$title=html_entity_decode(isset($t[1])?$t[1]:'Meetup event',ENT_QUOTES|ENT_HTML5,'UTF-8');$img=isset($i[1])?$i[1]:'';return'<article class="twj-event-card"><a href="'.esc_url($url).'" target="_blank" rel="noopener">'.($img?'<img src="'.esc_url($img).'" alt="" loading="lazy">':'').'<h2>'.esc_html($title).'</h2></a></article>'; }
 function shortcode(){ $html=''; foreach($this->urls() as $u)$html.=$this->card($u); return'<div class="twj-events-grid">'.$html.'</div>'; }
 function assets(){wp_register_style('twj-meetup',false,array(),'1.4.8');wp_enqueue_style('twj-meetup');wp_add_inline_style('twj-meetup','.twj-site-footer{display:none!important}.twj-events-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.twj-event-card{border:1px solid #e5e8ee;border-radius:12px;overflow:hidden;background:#fff}.twj-event-card a{text-decoration:none!important;color:#172033!important}.twj-event-card img{width:100%;aspect-ratio:16/9;object-fit:cover}.twj-event-card h2{padding:10px 12px;margin:0!important;font-size:.92rem}@media(max-width:900px){.twj-events-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}');wp_register_script('twj-site-cleanup',false,array(),'1.0.0',true);wp_enqueue_script('twj-site-cleanup');wp_add_inline_script('twj-site-cleanup',"document.addEventListener('DOMContentLoaded',function(){var selectors=['.site-title a','.site-branding a','.custom-logo-link+div a'];selectors.forEach(function(sel){document.querySelectorAll(sel).forEach(function(el){var t=(el.textContent||'').replace(/\\\\n/g,'').trim();if(t==='TimeWalk Japan')el.textContent='TimeWalk Japan';});});});");}
}
new TWJ_Meetup_Module();
