<?php
/* TimeWalk Japan: common Neighborhood History save normalization and Koenji migration. */
if(!defined('ABSPATH'))exit;
final class TWJ_Neighborhood_Save_Module{
 const V='1.0.0',CAT='neighborhood-histories',CAT_NAME='Neighborhood Histories',KOENJI=12045;
 private static $busy=false;
 function __construct(){add_action('save_post_post',array($this,'save'),18,2);add_action('rest_after_insert_post',array($this,'rest_save'),18,3);add_action('wp_loaded',array($this,'migrate'),72);add_action('template_redirect',array($this,'redirect_old'),1);add_action('rest_api_init',array($this,'rest'));}
 private function cat(){ $t=term_exists(self::CAT_NAME,'category');if(!$t)$t=wp_insert_term(self::CAT_NAME,'category',array('slug'=>self::CAT));if(is_wp_error($t))return 0;return is_array($t)?(int)$t['term_id']:(int)$t; }
 private function is_nh($id){if((string)get_post_meta($id,'_twj_neighborhood_history',true)==='1'||has_category(self::CAT,$id))return true;foreach(array('_twj_nh_prefecture','_twj_nh_prefecture_slug','_twj_nh_area','_twj_nh_broad_area','_twj_nh_municipality','_twj_nh_area_en','_twj_nh_area_ja','_twj_nh_historical_character','_twj_nh_nearest_stations')as$k)if(trim((string)get_post_meta($id,$k,true))!=='')return true;return false;}
 private function terms($id,$tax,$raw){if(!taxonomy_exists($tax))return;$v=array_values(array_filter(array_map('trim',preg_split('/[\r\n,、]+/u',(string)$raw))));if($v)wp_set_object_terms($id,$v,$tax,false);}
 private function normalize($id,$p){if(self::$busy||!$p||$p->post_type!=='post'||wp_is_post_revision($id)||!$this->is_nh($id))return;self::$busy=true;$cat=$this->cat();if($cat){$c=array_map('intval',wp_get_post_categories($id,array('fields'=>'ids')));$c[]=intval($cat);wp_set_post_categories($id,array_values(array_unique($c)),false);}update_post_meta($id,'_twj_neighborhood_history','1');
  $pref=trim((string)get_post_meta($id,'_twj_nh_prefecture',true));$ps=sanitize_title((string)get_post_meta($id,'_twj_nh_prefecture_slug',true));if($ps==='')$ps=sanitize_title((string)get_post_meta($id,'_twj_nh_city_slug',true));if($pref===''&&$ps==='tokyo')$pref='Tokyo';if($ps===''&&$pref!=='')$ps=sanitize_title($pref);if($pref!==''){update_post_meta($id,'_twj_nh_prefecture',$pref);$this->terms($id,'twj_nh_prefecture',$pref);}if($ps!==''){update_post_meta($id,'_twj_nh_prefecture_slug',$ps);update_post_meta($id,'_twj_nh_city_slug',$ps);}
  $area=trim((string)get_post_meta($id,'_twj_nh_area',true));if($area==='')$area=trim((string)get_post_meta($id,'_twj_nh_broad_area',true));if($area!==''){update_post_meta($id,'_twj_nh_area',$area);update_post_meta($id,'_twj_nh_broad_area',$area);$this->terms($id,'twj_nh_area',$area);$this->terms($id,'twj_nh_broad_area',$area);}
  $this->terms($id,'twj_nh_municipality',get_post_meta($id,'_twj_nh_municipality',true));$this->terms($id,'twj_nh_character',get_post_meta($id,'_twj_nh_historical_character',true));$this->terms($id,'twj_nh_period',get_post_meta($id,'_twj_nh_main_periods',true));$this->terms($id,'twj_nh_station',get_post_meta($id,'_twj_nh_nearest_stations',true));
  $walk=trim((string)get_post_meta($id,'_twj_nh_related_walk_url',true));$wa=strtolower(trim((string)get_post_meta($id,'_twj_nh_walk_available',true)));update_post_meta($id,'_twj_nh_walk_available',($walk!==''||in_array($wa,array('1','yes','true','available'),true))?'1':'0');
  $as=sanitize_title((string)get_post_meta($id,'_twj_nh_area_slug',true));if($as===''){$as=preg_replace('/-history$/','',sanitize_title($p->post_name));if($as!=='')update_post_meta($id,'_twj_nh_area_slug',$as);}if($as!==''){$want=preg_match('/-history$/',$as)?$as:$as.'-history';if($p->post_name!==$want)wp_update_post(array('ID'=>(int)$id,'post_name'=>$want));}clean_post_cache($id);self::$busy=false;}
 function save($id,$p){$this->normalize((int)$id,$p);}function rest_save($p,$r,$c){if($p&&$p->post_type==='post')$this->normalize((int)$p->ID,$p);}
 function migrate(){ $p=get_post(self::KOENJI);if(!$p||$p->post_type!=='post')return;$f=array('_twj_neighborhood_history'=>'1','_twj_nh_country'=>'Japan','_twj_nh_prefecture'=>'Tokyo','_twj_nh_prefecture_slug'=>'tokyo','_twj_nh_city'=>'Tokyo','_twj_nh_city_slug'=>'tokyo','_twj_nh_area'=>'Western Tokyo','_twj_nh_broad_area'=>'Western Tokyo','_twj_nh_municipality'=>'Suginami City','_twj_nh_area_en'=>'Koenji','_twj_nh_area_ja'=>'高円寺','_twj_nh_area_slug'=>'koenji','_twj_nh_alternative_names'=>'Kōenji, 高円寺村, 桃園','_twj_nh_nearest_stations'=>'Koenji, Shin-koenji, Higashi-koenji','_twj_nh_historical_character'=>'Village settlement, River landscape, Temples and shrines, Railway suburb, Shopping streets, Festival culture, Music and counterculture','_twj_nh_main_periods'=>'Edo period, Meiji and Taisho, Prewar Showa, Postwar growth, Contemporary Tokyo','_twj_nh_walk_available'=>'1','_twj_nh_related_walk_url'=>home_url('/momozono-river-koenji-history-walk/'),'_twj_nh_short_description'=>'From farming village and buried river to railway suburb, temple district, shopping streets and Tokyo counterculture.');foreach($f as$k=>$v)update_post_meta(self::KOENJI,$k,$v);if(get_post_meta(self::KOENJI,'_twj_nh_featured_priority',true)==='')update_post_meta(self::KOENJI,'_twj_nh_featured_priority',0);$this->normalize(self::KOENJI,get_post(self::KOENJI));$u=get_permalink(self::KOENJI);if($u){update_post_meta(self::KOENJI,'_yoast_wpseo_canonical',$u);update_post_meta(self::KOENJI,'rank_math_canonical_url',$u);}clean_post_cache(self::KOENJI);update_option('twj_koenji_neighborhood_migration_version',self::V,false);}
 function redirect_old(){if(!is_singular('post'))return;$id=get_queried_object_id();if(!$id||!$this->is_nh($id))return;$u=get_permalink($id);$req=isset($_SERVER['REQUEST_URI'])?wp_parse_url(wp_unslash($_SERVER['REQUEST_URI']),PHP_URL_PATH):'';$formal=wp_parse_url($u,PHP_URL_PATH);if($req&&$formal&&untrailingslashit($req)!==untrailingslashit($formal)){wp_safe_redirect($u,301,'TimeWalk Japan Neighborhood Histories');exit;}}
 function rest(){register_rest_route('timewalk/v1','/koenji-neighborhood-status',array('methods'=>'GET','callback'=>array($this,'status'),'permission_callback'=>'__return_true'));}
 private function match($k){$cat=get_category_by_slug(self::CAT);$a=array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>24,'twj_nh_directory'=>1,'twj_nh_keyword'=>$k,'tax_query'=>array(array('taxonomy'=>'twj_nh_prefecture','field'=>'slug','terms'=>'tokyo')));if($cat)$a['cat']=(int)$cat->term_id;$q=new WP_Query($a);return in_array(self::KOENJI,array_map('intval',wp_list_pluck($q->posts,'ID')),true);}
 function status(){ $p=get_post(self::KOENJI);if(!$p)return rest_ensure_response(array('post_id'=>self::KOENJI,'exists'=>false));$tax=array();foreach(array('twj_nh_prefecture','twj_nh_area','twj_nh_municipality','twj_nh_character','twj_nh_station')as$t){$v=wp_get_post_terms(self::KOENJI,$t,array('fields'=>'names'));$tax[$t]=is_wp_error($v)?array():array_values($v);}$cats=wp_get_post_categories(self::KOENJI,array('fields'=>'names'));return rest_ensure_response(array('module_version'=>self::V,'post_id'=>self::KOENJI,'exists'=>true,'status'=>$p->post_status,'permalink'=>get_permalink(self::KOENJI),'legacy_url'=>home_url('/koenji-history/'),'categories'=>array_values($cats),'meta'=>array('prefecture'=>get_post_meta(self::KOENJI,'_twj_nh_prefecture',true),'prefecture_slug'=>get_post_meta(self::KOENJI,'_twj_nh_prefecture_slug',true),'area'=>get_post_meta(self::KOENJI,'_twj_nh_area',true),'municipality'=>get_post_meta(self::KOENJI,'_twj_nh_municipality',true),'area_en'=>get_post_meta(self::KOENJI,'_twj_nh_area_en',true),'area_ja'=>get_post_meta(self::KOENJI,'_twj_nh_area_ja',true),'alternative_names'=>get_post_meta(self::KOENJI,'_twj_nh_alternative_names',true),'nearest_stations'=>get_post_meta(self::KOENJI,'_twj_nh_nearest_stations',true),'walk_available'=>get_post_meta(self::KOENJI,'_twj_nh_walk_available',true),'short_description'=>get_post_meta(self::KOENJI,'_twj_nh_short_description',true),'yoast_canonical'=>get_post_meta(self::KOENJI,'_yoast_wpseo_canonical',true),'rank_math_canonical'=>get_post_meta(self::KOENJI,'rank_math_canonical_url',true)),'taxonomies'=>$tax,'checks'=>array('search_koenji'=>$this->match('Koenji'),'search_japanese'=>$this->match('高円寺'),'search_municipality'=>$this->match('Suginami City'),'western_tokyo_term'=>in_array('Western Tokyo',$tax['twj_nh_area'],true),'tokyo_term'=>in_array('Tokyo',$tax['twj_nh_prefecture'],true),'category_assigned'=>in_array(self::CAT_NAME,$cats,true))));}
}
new TWJ_Neighborhood_Save_Module();